.

diff --git a/sord b/sord
--- a/sord
+++ b/sord
@@ -42,13 +42,11 @@ fi
 infile=$( readlink 'in.m' 2> /dev/null ) || infile='in.m'
 
 # Make diretories
+mkdir -p tmp
 if [ -d /gpfs ]; then
-  mkdir -p /gpfs/$LOGNAME/sord/tmp
   mkdir -p /gpfs/$LOGNAME/sord/run
-  ln -sf /gpfs/$LOGNAME/sord/tmp
   ln -sf /gpfs/$LOGNAME/sord/run
 else
-  mkdir -p tmp
   mkdir -p run
 fi
 
@@ -81,7 +79,7 @@ case "$key" in
   np) np3=( $1 $2 $3 ) ;;
   dx) dx=$1 ;;
   npml) npml=$1 ;;
-  datadir) datadir="$1" ;;
+  datadir) datair="$1" ;;
   return) break ;;
 esac
 done < tmp/input
@@ -225,7 +223,7 @@ sh/tarball
 rundir="run/$count"
 echo "Run directory: $rundir"
 mkdir "$rundir"
-echo "$starttime: Start SORD setup" >> "$rundir/log"
+echo "$starttime: SORD setup started" >> "$rundir/log"
 cp 'in.m' tmp/sord.tgz tmp/sord-$mode tmp/input "$rundir"
 if [ $optimize = g ]; then
   cp f/*.f90 "$rundir"
@@ -252,8 +250,6 @@ cat << END > runmeta.m
   mode    = '$mode';
   np      = [ ${np3[*]} ];
 END
-
-echo "$(date): Finish setup" >> log
 
 # run scripts
 code="sord"
@@ -293,7 +289,7 @@ if [ "$velmodel" ]; then
   fi
   code="scecvm"
   bin="./scecvm4-$mode nc rlon rlat rdep rho vp vs"
-  post="mv meta.m endian x1 x2 x3 ts1 rho vp vs $rundir/data"
+  post="mv endian meta.m ts1 x1 x2 x3 rho vp vs $rundir/data"
   walltime="00:30:00"
   topdir="$rundir"
   rundir="$topdir/scecvm"
@@ -306,16 +302,28 @@ if [ "$velmodel" ]; then
   [ "$run" ] && ./run "-$run"
   cd "$topdir"
 elif [ "$datadir" ]; then
-  endian="$( perl -le 'print pack('V',1) eq pack('L',1) ? "l" : "b"' )"
-  cd "$srcdir/$datadir"
-  if [ "$endian" != "$( cat endian )" ]; then
-    echo "Error: endian file not found or endian missmatch"
-    exit 1
-  fi
-  datadir=$( /bin/pwd )
+  mkdir data
+  cd data
+  files="endian meta.m ts1 x1 x2 x3 rho vp vs"
+  for file in $files; do
+    fullfile="$srcdir/$datadir/$file"
+    if [ -f "$fullfile" ]; then
+      ln "$fullfile" .
+    else
+      echo "$fullfile not found, can't run yet"
+      exit 1
+    fi
+    endian=$( cat endian )
+    native="$( perl -le 'print pack('V',1) eq pack('L',1) ? "l" : "b"' )"
+    if [ "$endian" != "$native" ]; then
+      echo "Error: data endian=$endian, native endian=$native"
+      exit 1
+    fi
+  done
   cd "$rundir"
-  ln -s "$datadir" 'data'
 fi
+
+echo "$(date): setup finished" >> log
 
 # Run SORD
 [ "$run" ] && ./run "-$run"
