.

diff --git a/sh/teragrid b/sh/teragrid
--- a/sh/teragrid
+++ b/sh/teragrid
@@ -5,43 +5,56 @@ if [ $( /bin/pwd | grep -v gpfs ) ]; then
   exit
 fi
 
-cat << END > run-$name
+case "$mode" in
+s) cat << END > run-$name
 #!/bin/bash -e
 if ! grep -q "\$HOSTNAME" mf; then
   echo "Error: interactive jobs must be launched from the following hosts:"
   sed 's/^/  /; s/:2//' mf
   exit
 fi
-log="$rundir/log"
-echo "\$( date ): Start $name" >> "\$log"
+cd "$rundir"
+echo "\$( date ): Start $name" >> log
 $pre
-END
-
-case "$mode" in
-
-s) cat << END >> run-$name
 case \${1:?} in
   -i) $bin ;;
   -g) totalview $bin ;;
   -b) nohup $bin > out.log & :; pid=\$!
-      echo "Background job started with PID \$pid" >> "\$log"
-      echo "Background job started with PID \$pid" ;;
 esac
-$post
-echo "\$( date ): Finish $name" >> "\$log"
+cd "$rundir"
+if [ "\$pid" ]; then
+  echo "Background job started with PID \$pid" >> log
+  echo "Background job started with PID \$pid" ;;
+else
+  $post
+fi
+echo "\$( date ): Finish $name" >> log
 END
 ;;
 
-p) cat << END >> run-$name
+p) cat << END > run-$name
+#!/bin/bash -e
+if ! grep -q "\$HOSTNAME" mf; then
+  echo "Error: interactive jobs must be launched from the following hosts:"
+  sed 's/^/  /; s/:2//' mf
+  exit
+fi
+cd "$rundir"
+echo "\$( date ): Start $name" >> log
+$pre
 case \${1:?} in
   -i) mpirun -machinefile mf -np $np $bin ;;
   -g) mpirun -tv -machinefile mf -np $np $bin ;;
   -b) nohup mpirun -machinefile mf -np $np $bin > out.log & :; pid=\$!
-      echo "Background job started with PID \$pid" >> "\$log"
-      echo "Background job started with PID \$pid" ;;
 esac
-$post
-echo "\$( date ): Finish $name" >> "\$log"
+cd "$rundir"
+if [ "\$pid" ]; then
+  echo "Background job started with PID \$pid" >> log
+  echo "Background job started with PID \$pid" ;;
+else
+  $post
+fi
+echo "\$( date ): Finish $name" >> log
 END
 ;;
 
@@ -68,12 +81,13 @@ cat << END > script-$name
 #PBS -M $email
 #PBS -m abe
 #PBS -V
-log="$rundir/log"
-echo "\$( date ): Start $name" >> "\$log"
+cd "$rundir"
+echo "\$( date ): Start $name" >> log
 $pre
 mpirun -machinefile \$PBS_NODEFILE -np $np $bin
+cd "$rundir"
 $post
-echo "\$( date ): Finish $name" >> "\$log"
+echo "\$( date ): Finish $name" >> log
 END
 
 chmod u+x run-$name que-$name script-$name
